# Gestion des utilisateurs
fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    App\Entity\User # La classe de l'entité User que nous utilisons
    registration:
        form:
            type: App\Form\RegistrationType
    from_email:
        address:         contact@aviron-bourges.org
        sender_name:    Aviron Club de Bourges
    
    service:
        mailer: fos_user.mailer.twig_swift