imports:
    - { resource: parameters.yaml }

# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SORTIES]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_SORTIES, ROLE_ALLOWED_TO_SWITCH]


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity:
                class: 'App\Entity\User'
                property: 'username'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:   ^/
            anonymous: true # On autorise alors les anonymes sur ce pare-feu
            provider: main
            remember_me:
                secret:     '%secret%' # %secret% est un paramètre de parameter
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
                entry_point: App\Security\LoginAuthenticator
            form_login:
                login_path: authentification_login
            logout:
                path: authentification_logout
            
    access_control:
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
