<?php

namespace App\Repository;

/**
 * EntrainementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrainementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListeEntrainements()
    {
        $qb = $this
            ->createQueryBuilder('e')
            ->where('e.datesupp is null')
            ->orderBy('e.datedebut', 'DESC')
            ->addOrderBy('e.heuredebut');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getListeEntrainementsAVenir()
    {
        $qb = $this
            ->createQueryBuilder('e')
            ->where('e.datedebut >= :aujourdhui')
            ->andWhere('e.datesupp is null')
            ->orderBy('e.datedebut', 'ASC')
            ->addOrderBy('e.heuredebut')
            ->setParameter('aujourdhui', date("Y-m-d", time()));

        return $qb
            ->getQuery()
            ->getResult();
    }
}
