<?php

namespace App\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function DonneReservations($utilisateur)
    {
        $qb = $this
            ->createQueryBuilder('r')
            ->where('r.idut = :idut')
            ->andWhere('r.datesupp is null')
            ->setParameter('idut', $utilisateur);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
