<?php

namespace App\Repository;

/**
 * TypeBateauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBateauRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListeTypesBateau()
    {
        return $this->getListeTypesBateauQueryBuilder()
            ->getQuery()
            ->getResult();
    }

    public function getListeTypesBateauQueryBuilder()
    {
        return $this
            ->createQueryBuilder('t')
            ->orderBy('t.nom');
    }
}
