<?php

namespace App\Repository;

use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\Persistence\ManagerRegistry;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, User::class);
    }

    public function getCanRowQueryBuilder()
    {
        return $this
            ->createQueryBuilder('u')
            ->where('u.datesupp is null')
            ->orderBy('u.prenom')
            ->addOrderBy('u.nom');
    }

    public function getMembres($page, $nbParPage)
    {
        $query = $this->createQueryBuilder('u')
                    ->where('u.datesupp is null')
                    ->orderBy('u.prenom')
                    ->addOrderBy('u.nom')
                    ->setFirstResult(($page-1)*$nbParPage)
                    ->setMaxResults($nbParPage);

        return new Paginator($query, true);
    }

    public function findLikePrenomNom($q)
    {
        return $this->createQueryBuilder('u')
            ->where('u.prenom LIKE :query')
            ->setParameter(':query', $q)
            ->getQuery()
            ->getResult();
    }
}
