aviron_users_liste:
    path:       /membres/{page}/{saison}
    controller: App\Controller\UserController:index
    defaults:
        page: 1
        saison: 0
    requirements:
        page: \d+
        saison: \d+

aviron_users_ajouter:
    path:       /membres/ajouter
    controller: App\Controller\UserController:ajouter

aviron_users_modifier:
    path:       /membres/modifier/{id}
    controller: App\Controller\UserController:modifier
    requirements:
        id: \d+

aviron_users_supprimer:
    path:       /membres/supprimer/{id}
    controller: App\Controller\UserController:supprimer
    requirements:
        id: \d+

aviron_users_recherche:
    path:       /membres/recherche
    controller: App\Controller\UserController:recherche

aviron_users_profil:
    path:       /profil
    controller: App\Controller\UserController:afficherProfil

aviron_users_envoyer_login_par_mail:
    path:       /membres/envoyerloginparmail/{id}
    controller: App\Controller\UserController:envoyerLoginParMail
    requirements:
        id: \d+

aviron_users_get:
    path:       /membres/get/
    controller: App\Controller\User/get

aviron_membre_licences_preinscription:
    path:       /preinscription
    controller: App\Controller\MembreLicencesController:preinscription

aviron_membre_licences_reinscription:
    path:       /reinscription
    controller: App\Controller\MembreLicencesController:reinscription

aviron_membre_licences_preinscriptions:
    path:       /membres/preinscriptions
    controller: App\Controller\MembreLicencesController:preinscriptions

aviron_membre_licences_valider_inscription:
    path:       /membres/validerinscription/{id}
    controller: App\Controller\MembreLicencesController:validerInscription
    requirements:
        id: \d+

aviron_membre_licences_supprimer_inscription:
    path:       /membres/supprimerinscription/{id}
    controller: App\Controller\MembreLicencesController:supprimerInscription
    requirements:
        id: \d+

aviron_membre_licences_marquer_comme_saisie:
    path:       /membres/marquercommesaisie/{id}
    controller: App\Controller\MembreLicencesController:marquerCommeSaisie
    requirements:
        id: \d+

aviron_membre_licences_marquer_comme_imprimee:
    path:       /membres/marquercommeimprimee/{id}
    controller: App\Controller\MembreLicencesController:marquerCommeImprimee
    requirements:
        id: \d+

aviron_membre_licences_export_licences_a_saisir:
    path:       /membres/exportlicencesasaisir
    controller: App\Controller\ExportExcelController:exportLicencesASaisir
    requirements:
        id: \d+

aviron_membre_licences_telecharger_fiche_inscription:
    path:       /telechargerficheinscription
    controller: App\Controller\MembreLicencesController:telechargerFicheInscription

aviron_membre_licences_voir_fiche_inscription:
    path:       /membres/voirficheinscription/{id}
    controller: App\Controller\MembreLicencesController:voirFicheInscription
    requirements:
        id: \d+

authentification_login:
    path: /
    controller: App\Controller\AuthentificationController:login

authentification_logout:
    path: /logout
    controller: App\Controller\AuthentificationController:logout

authentification_changermotdepasse:
    path: /changerdemotdepasse
    controller: App\Controller\AuthentificationController:changerMotDePasse

authentification_motdepasseoublie:
    path: /motdepasseoublie
    controller: App\Controller\AuthentificationController:motDePasseOublie

authentification_nouveaumotdepasse:
    path: /nouveaumotdepasse/{token}
    controller: App\Controller\AuthentificationController:nouveauMotDePasse
    requirements:
        token: .+

authentification_reinscription_token:
    path:       /reinscription/{token}
    controller: App\Controller\AuthentificationController:reinscriptionToken
    requirements:
        token: .+

authentification_reinscription_lien_par_mail:
    path:       /membres/envoyerlienreinscriptionparmail/{idmembre}
    controller: App\Controller\AuthentificationController:envoyerLienReinscriptionParMail
    requirements:
        idmembre: \d+


aviron_accueil:
    path:     /accueil
    controller: App\Controller\SortieController:accueil
    
aviron_bateaux_home:
    path:     /bateaux/{page}
    controller:    App\Controller\BateauController:index
    defaults:
        page:           1
    requirements:
        page: \d*
        
aviron_bateaux_ajouter:
    path:     /bateaux/ajouter
    controller:    App\Controller\BateauController:ajouter
        
aviron_bateaux_modifier:
    path:       /bateaux/modifier/{id}
    controller:    App\Controller\BateauController:modifier
    requirements:
        id: \d+
        
aviron_bateaux_supprimer:
    path:       /bateaux/supprimer/{id}
    controller:    App\Controller\BateauController:supprimer
    requirements:
        id: \d+

aviron_bateaux_mettrehorsservice:
    path:       /bateaux/mettrehorsservice/{id}
    controller:    App\Controller\BateauController:mettrehorsservice
    requirements:
        id: \d+

aviron_bateaux_remettreenservice:
    path:       /bateaux/remettreenservice/{id}
    controller:    App\Controller\BateauController:remettreenservice
    requirements:
        id: \d+
    
aviron_sortie_home:
    path:     /sorties/{page}
    controller: App\Controller\SortieController:index
    defaults:
        page: 1
    requirements:
        page: \d+
    
aviron_sortie_ajouter:
    path:     /sorties/ajouter/{nbrameurs}
    controller: App\Controller\SortieController:ajouter
    defaults:
        nbrameurs: 0
    requirements:
        nbrameurs: \d+
    
aviron_sortie_terminer:
    path:     /sorties/terminer/{id}
    controller: App\Controller\SortieController:terminer
    requirements:
        id: \d+
        
aviron_sortie_voir:
    path:     /sorties/sortie/{id}
    controller: App\Controller\SortieController:voir
    requirements:
        id: \d+
        
aviron_sortie_modifier:
    path:     /sorties/modifier/{id}
    controller: App\Controller\SortieController:modifier
    requirements:
        id: \d+
        
aviron_sortie_supprimer:
    path:     /sorties/supprimer/{id}
    controller: App\Controller\SortieController:supprimer
    requirements:
        id: \d+

aviron_sortie_membre:
    path:     /sorties/membre/{idmembre}
    controller: App\Controller\SortieController:membre
    requirements:
        id: \d+

aviron_sortie_bateau:
    path:     /sorties/bateau/{idbateau}
    controller: App\Controller\SortieController:bateau
    requirements:
        id: \d+

aviron_sortie_statistiques_membres:
    path:     /sorties/statistiques/membres/kilometresparcourus/{annee}/{mois}
    controller: App\Controller\SortieController:statistiquesMembres
    defaults:
        annee: 0
        mois: 0
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_statistiques_nombre_sorties_membres:
    path:     /sorties/statistiques/membres/nombredesorties/{annee}/{mois}
    controller: App\Controller\SortieController:statistiquesNombreDeSortiesMembres
    defaults:
        annee: 0
        mois: 0
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_statistiques_bateaux:
    path:     /sorties/statistiques/bateaux/kilometresparcourus/{annee}/{mois}
    controller: App\Controller\SortieController:statistiquesBateaux
    defaults:
        annee: 0
        mois: 0
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_statistiques_nombre_sorties_bateaux:
    path:     /sorties/statistiques/bateaux/nombredesorties/{annee}/{mois}
    controller: App\Controller\SortieController:statistiquesNombreDeSortiesBateaux
    defaults:
        annee: 0
        mois: 0
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_typebateau_home:
    path:     /typebateau/{page}
    controller: App\Controller\TypeBateauController:index
    defaults:
        page: 1
    requirements:
        page: \d*
    
aviron_sortie_typebateau_ajouter:
    path:     /typebateau/ajouter
    controller: App\Controller\TypeBateauController:ajouter
        
aviron_sortie_typebateau_modifier:
    path:     /typebateau/modifier/{id}
    controller: App\Controller\TypeBateauController:modifier
    requirements:
        id: \d+
        
aviron_sortie_typebateau_supprimer:
    path:     /typebateau/supprimer/{id}
    controller: App\Controller\TypeBateauController:supprimer
    requirements:
        id: \d+

aviron_sortie_saison_liste:
    path:     /config/saison
    controller: App\Controller\SaisonController:index
    
aviron_sortie_saison_ajouter:
    path:     /config/saison/ajouter
    controller: App\Controller\SaisonController:ajouter
        
aviron_sortie_saison_modifier:
    path:     /config/saison/modifier/{id}
    controller: App\Controller\SaisonController:modifier
    requirements:
        id: \d+

aviron_sortie_saison_supprimer:
    path:     /config/saison/supprimer/{id}
    controller: App\Controller\SaisonController:supprimer
    requirements:
        id: \d+

aviron_sortie_excel:
    path:     /export/membres/kilometresparcourus/{annee}/{mois}
    controller: App\Controller\ExportExcelController:exportKmParcourusParMembre
    defaults: 
        annee: 0
        mois: 0
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_export_nombre_sorties_membres:
    path:     /export/membres/nombredesorties/{annee}/{mois}
    controller: App\Controller\ExportExcelController:exportNombreDeSortiesParMembre
    defaults:
        annee: 0
        mois: 0
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_export_kmparcourus_bateaux:
    path:     /export/bateaux/kilometresparcourus/{annee}/{mois}
    controller: App\Controller\ExportExcelController:exportKmParcourusParBateau
    defaults:
        annee: 0
        mois: 0
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_export_nombre_sorties_bateaux:
    path:     /export/bateaux/nombredesorties/{annee}/{mois}
    controller: App\Controller\ExportExcelController:exportNombreDeSortiesParBateau
    defaults:
        annee: 0
        mois: 0
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_reservation_entrainements:
    path: /reservation/entrainements
    controller: App\Controller\ReservationController:listerEntrainementsAVenir

aviron_sortie_reservation_reserver:
    path: /reservation/entrainements/reserver/{id}
    controller: App\Controller\ReservationController:reserver
    requirements:
        id: \d+

aviron_sortie_reservation_admin_reserver:
    path: /reservation/entrainements/reserverpourunmembre/{identrainement}
    controller: App\Controller\ReservationController:reserverPourUnMembre
    requirements:
        identrainement: \d+

aviron_sortie_reservation_desinscrire:
    path: /reservation/entrainements/desinscrire/{id}
    controller: App\Controller\ReservationController:desinscrire
    requirements:
        id: \d+

aviron_sortie_reservation_admin_desinscrire:
    path: /reservation/entrainements/desinscrire/{identrainement}/{idmembre}
    controller: App\Controller\ReservationController:desinscrireUnMembre
    requirements:
        identrainement: \d+
        idmembre: \d+

aviron_sortie_reservation_participants:
    path: /reservation/entrainements/participants/{id}
    controller: App\Controller\ReservationController:participants
    requirements:
        id: \d+

aviron_sortie_reservation_admin_ajouter_entrainement:
    path: /reservation/administrer/entrainements/ajouter
    controller: App\Controller\ReservationController:ajouterEntrainement

aviron_sortie_reservation_admin_supprimer_entrainement:
    path: /reservation/administrer/entrainements/supprimer/{id}
    controller: App\Controller\ReservationController:supprimerEntrainement
    requirements:
        id: \d+

aviron_sortie_reservation_admin_modifier_entrainement:
    path: /reservation/administrer/entrainements/modifier/{id}
    controller: App\Controller\ReservationController:modifierEntrainement
    requirements:
        id: \d+
        