<?php

namespace Aviron\UserBundle\Repository;

/**
 * TypeLicenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLicenceRepository extends \Doctrine\ORM\EntityRepository
{
}
