<?php

namespace Aviron\SortieBundle\Repository;

/**
 * BateauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BateauRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbRameursQueryBuilder($nbRameurs)
    {
        if ($nbRameurs != 0) {
            return $this
                ->createQueryBuilder('b')
                ->where('b.nbplacerameurs = :nbRameurs')
                ->setParameter('nbRameurs', $nbRameurs);
        } else {
            return $this
                ->createQueryBuilder('b');
        }
    }
}
