<?php

namespace Aviron\SortieBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListeEntrainements()
    {
        $qb = $this
            ->createQueryBuilder('e')
            ->orderBy('e.datedebut', 'DESC')
            ->addOrderBy('e.heuredebut');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
