<?php

namespace Aviron\SortieBundle\Repository;

/**
 * SortieAthleteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieAthleteRepository extends \Doctrine\ORM\EntityRepository
{
}
