<?php

namespace Aviron\SortieBundle\Repository;

/**
 * TypePrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
