<?php

namespace Aviron\SortieBundle\Repository;

/**
 * TypeBateauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeBateauRepository extends \Doctrine\ORM\EntityRepository
{
}
