aviron_bateaux_home:
    path:     /bateaux/{page}
    defaults:
        _controller:    AvironSortieBundle:Bateau:index
        page:           1
    requirements:
        page: \d*
        
aviron_bateaux_ajouter:
    path:     /bateaux/ajouter
    defaults:
        _controller: AvironSortieBundle:Bateau:ajouter
        
aviron_bateaux_modifier:
    path:       /bateaux/modifier/{id}
    defaults:
        _controller: AvironSortieBundle:Bateau:modifier
    requirements:
        id: \d+
        
aviron_bateaux_supprimer:
    path:       /bateaux/supprimer/{id}
    defaults:
        _controller: AvironSortieBundle:Bateau:supprimer
    requirements:
        id: \d+

aviron_bateaux_mettrehorsservice:
    path:       /bateaux/mettrehorsservice/{id}
    defaults:
        _controller: AvironSortieBundle:Bateau:mettrehorsservice
    requirements:
        id: \d+

aviron_bateaux_remettreenservice:
    path:       /bateaux/remettreenservice/{id}
    defaults:
        _controller: AvironSortieBundle:Bateau:remettreenservice
    requirements:
        id: \d+
    
aviron_sortie_home:
    path:     /sorties/{page}
    defaults: 
        _controller: AvironSortieBundle:Sortie:index
        page: 1
    requirements:
        page: \d+
    
aviron_sortie_ajouter:
    path:     /sorties/ajouter/{nbrameurs}
    defaults:
        _controller: AvironSortieBundle:Sortie:ajouter
        nbrameurs: 0
    requirements:
        nbrameurs: \d+
    
aviron_sortie_terminer:
    path:     /sorties/terminer/{id}
    defaults: 
        _controller: AvironSortieBundle:Sortie:terminer
    requirements:
        id: \d+
        
aviron_sortie_voir:
    path:     /sorties/sortie/{id}
    defaults: 
        _controller: AvironSortieBundle:Sortie:voir
    requirements:
        id: \d+
        
aviron_sortie_modifier:
    path:     /sorties/modifier/{id}
    defaults: 
        _controller: AvironSortieBundle:Sortie:modifier
    requirements:
        id: \d+
        
aviron_sortie_supprimer:
    path:     /sorties/supprimer/{id}
    defaults: 
        _controller: AvironSortieBundle:Sortie:supprimer
    requirements:
        id: \d+

aviron_sortie_membre:
    path:     /sorties/membre/{idmembre}
    defaults: 
        _controller: AvironSortieBundle:Sortie:membre
    requirements:
        id: \d+

aviron_sortie_statistiques_membres:
    path:     /sorties/statistiques/membres/kilometresparcourus/{annee}/{mois}
    defaults:
        annee: 0
        mois: 0
        _controller: AvironSortieBundle:Sortie:statistiquesMembres
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_statistiques_nombre_sorties_membres:
    path:     /sorties/statistiques/membres/nombredesorties/{annee}/{mois}
    defaults:
        annee: 0
        mois: 0
        _controller: AvironSortieBundle:Sortie:statistiquesNombreDeSortiesMembres
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_statistiques_bateaux:
    path:     /sorties/statistiques/bateaux/kilometresparcourus/{annee}/{mois}
    defaults:
        annee: 0
        mois: 0
        _controller: AvironSortieBundle:Sortie:statistiquesBateaux
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_statistiques_nombre_sorties_bateaux:
    path:     /sorties/statistiques/bateaux/nombredesorties/{annee}/{mois}
    defaults:
        annee: 0
        mois: 0
        _controller: AvironSortieBundle:Sortie:statistiquesNombreDeSortiesBateaux
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_typebateau_home:
    path:     /typebateau/{page}
    defaults: 
        _controller: AvironSortieBundle:TypeBateau:index
        page: 1
    requirements:
        page: \d*
    
aviron_sortie_typebateau_ajouter:
    path:     /typebateau/ajouter
    defaults: 
        _controller: AvironSortieBundle:TypeBateau:ajouter
        
aviron_sortie_typebateau_modifier:
    path:     /typebateau/modifier/{id}
    defaults: 
        _controller: AvironSortieBundle:TypeBateau:modifier
    requirements:
        id: \d+
        
aviron_sortie_typebateau_supprimer:
    path:     /typebateau/supprimer/{id}
    defaults: 
        _controller: AvironSortieBundle:TypeBateau:supprimer
    requirements:
        id: \d+

aviron_sortie_saison_liste:
    path:     /config/saison
    defaults: { _controller: AvironSortieBundle:Saison:index }
    
aviron_sortie_saison_ajouter:
    path:     /config/saison/ajouter
    defaults: { _controller: AvironSortieBundle:Saison:ajouter }
        
aviron_sortie_saison_modifier:
    path:     /config/saison/modifier/{id}
    defaults: 
        _controller: AvironSortieBundle:Saison:modifier
    requirements:
        id: \d+

aviron_sortie_saison_supprimer:
    path:     /config/saison/supprimer/{id}
    defaults: 
        _controller: AvironSortieBundle:Saison:supprimer
    requirements:
        id: \d+

aviron_sortie_excel:
    path:     /export/membres/kilometresparcourus/{annee}/{mois}
    defaults: 
        annee: 0
        mois: 0
        _controller: AvironSortieBundle:ExportExcel:exportKmParcourusParMembre
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_export_nombre_sorties_membres:
    path:     /export/membres/nombredesorties/{annee}/{mois}
    defaults:
        annee: 0
        mois: 0
        _controller: AvironSortieBundle:ExportExcel:exportNombreDeSortiesParMembre
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_export_kmparcourus_bateaux:
    path:     /export/bateaux/kilometresparcourus/{annee}/{mois}
    defaults:
        annee: 0
        mois: 0
        _controller: AvironSortieBundle:ExportExcel:exportKmParcourusParBateau
    requirements:
        annee: \d+
        mois: \d+

aviron_sortie_export_nombre_sorties_bateaux:
    path:     /export/bateaux/nombredesorties/{annee}/{mois}
    defaults:
        annee: 0
        mois: 0
        _controller: AvironSortieBundle:ExportExcel:exportNombreDeSortiesParBateau
    requirements:
        annee: \d+
        mois: \d+