aviron_users_liste:
    path:       /membres/{page}
    defaults:   
        _controller: AvironUserBundle:User:index
        page: 1
    requirements:
        page: \d+

aviron_users_ajouter:
    path:       /membres/ajouter
    defaults: 
        _controller: AvironUserBundle:User:ajouter

aviron_users_modifier:
    path:       /membres/modifier/{id}
    defaults: 
        _controller: AvironUserBundle:User:modifier
    requirements:
        id: \d+

aviron_users_supprimer:
    path:       /membres/supprimer/{id}
    defaults: 
        _controller: AvironUserBundle:User:supprimer
    requirements:
        id: \d+

aviron_users_recherche:
    path:       /membres/recherche
    defaults:
        _controller: AvironUserBundle:User:recherche

aviron_users_get:
    path:       /membres/get/
    defaults:
        _controller: AvironUserBundle:User/get

aviron_user_typelicence_liste:
    path:     /config/typelicence
    defaults: { _controller: AvironUserBundle:TypeLicence:index }
    
aviron_user_typelicence_ajouter:
    path:     /config/typelicence/ajouter
    defaults: { _controller: AvironUserBundle:TypeLicence:ajouter }

fos_user_change_password:
    path: /moncompte/motdepasse
    defaults: { _controller: fos_user.change_password.controller:changePasswordAction }
